### ISSUE TITLE
ChainedForeignKey doesn't support abbreviated ForeignKey model name syntax

### ISSUE THREAD

**Issue by acdha** [digi604/django-smart-selects#16] opened 2011-03-28 14:06 UTC
The standard Django ForeignKey field allows you to reference models which have not yet been defined using either the name of the model (e.g. `models.ForeignKey("Author")`) but ChainedForeignKey requires the full `<app>.<model>` syntax to avoid a `ValueError` in db_fields.py on line 16 when it attempts to split the field name.

Since the shorter form is actually recommended by default in the Django documentation (see http://docs.djangoproject.com/en/dev/ref/models/fields/#foreignkey) this difference should at least be documented.

**Comment by blag** [comment] 2016-10-22 09:57
Does this still happen with the code currently in the master branch? There's been a few changes to that handling that might have fixed this.

**Comment by blag** [comment] 2016-10-28 11:46
I pushed the fix for this out to PyPI as version 1.2.6. Please upgrade and reopen this issue if the issue isn't fixed. Thanks!

**Closed by blag** 2016-10-28 11:46 UTC
Labels: Needs feedback, Possibly fixed
