### ISSUE TITLE
Unespected form submission problem

### ISSUE THREAD

**Issue by SalahAdDin** [digi604/django-smart-selects#121] opened 2016-02-21 05:25 UTC
Hello, i have many problems with the new version, i dislike it!

In this case i have a problem using formset submission as django inline admin.
When i submit the form i have a problem with the Chained field:
![stopiteration at -camara-formulario-de-afiliacion-ccct- - opera_016](https://cloud.githubusercontent.com/assets/5034215/13201080/3032afe4-d830-11e5-9350-5268d0cdeae3.png)
![stopiteration at -camara-formulario-de-afiliacion-ccct- - opera_015](https://cloud.githubusercontent.com/assets/5034215/13201081/35614f84-d830-11e5-873f-599675f7bbf2.png)
So, i go to the html template render and i find this:
![seleccion_017](https://cloud.githubusercontent.com/assets/5034215/13201095/e7debeda-d830-11e5-8ffb-87536ddf45ae.png)
`------` and selected option, both are seleted option, and this generate a conflict in `smart_selects/widgets.py`.

So, what happen with the new version? Older version haven't problems, why this yes?

**Comment by jimmykobe1171** [comment] 2016-02-21 05:42
actually, new release merge some pull requests. especially some changes in js file. but I think the key reason is the lack of unittest. now it includes sone test for normal use in admin. but the use case as inline formset is not include. maybe we should add more tests for these situations.

**Comment by SalahAdDin** [comment] 2016-02-21 06:56
I hope this man, i need really really this package, and finish this form.

**Comment by jimmykobe1171** [comment] 2016-02-22 16:19
I will add more test this week, sorry for the inconvenience.

**Comment by jimmykobe1171** [comment] 2016-02-23 15:17
@SalahAdDin  could you post your Model structure? I try some inline admin for ChainedForeignKey but could not reproduce your error.

**Comment by SalahAdDin** [comment] 2016-02-23 19:44
Well, in admin inline doesn't works smart-selects new version, i'm doing a form with one single formset, it show me this error.

**Comment by jimmykobe1171** [comment] 2016-02-24 05:05
@SalahAdDin It would be helpful if you could provide more information about this error. I could not figure out what trigger this error.

**Comment by SalahAdDin** [comment] 2016-02-29 04:17
Ok, here are my code, with older versions works, but with new version doesn't works.

**models.py**
```python
class Person(models.Model):
    name = models.CharField(max_length=20, help_text=_('Type of entity that registers.'), verbose_name=_("Type's name"))

    class Meta:
        verbose_name = _("Entity's type")

    def __str__(self):
        return self.name


class MemberShip(models.Model):
    title = models.CharField(max_length=255, help_text=_("Affiliation type's name"), verbose_name=_('Title'), )
    type_person = models.ForeignKey(Person, verbose_name=_("Entity's type"), related_name="membership")
    description = models.CharField(max_length=500,
                                   help_text=_("Affiliation type's description."), verbose_name=_('Description'))
    value = models.DecimalField(decimal_places=2,
                                max_digits=10, verbose_name=_('Fee'), help_text=_("Affiliation's fee."))

    class Meta:
        verbose_name = _('Membership')
        verbose_name_plural = _('Memberships')

    def __str__(self):
        return self.title

class Affiliation(models.Model):
    person = models.ForeignKey(Person, verbose_name=_("Entity's name"), related_name="person")
    affiliation = ChainedForeignKey(
        MemberShip,
        chained_field="person",
        chained_model_field="type_person",
        show_all=False,
        auto_choose=True,
        verbose_name=_('Membership')
    )
    affiliate = models.ForeignKey(Affiliates, verbose_name=_('Affiliate'), related_name="affiliate")
    date_prein = models.DateField(_("Date's up"), auto_now_add=True, )
    date_in = models.DateField(_("Date's in"), blank=True, null=True, )
    is_active = models.BooleanField(verbose_name=_('Active'), help_text=_("Is it active?"), default=False, )

    class Meta:
        verbose_name = _('Affiliation')
        verbose_name_plural = _('Affiliations')

    def __str__(self):
        return '%s, %s' % (self.affiliation, self.affiliate)
```

**form.py**
```
class AffiliationInlineForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AffiliationInlineForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {
                'required': True
            }

    class Meta:
        model = Affiliation
        fields = ['person', 'affiliation', ]


class AffiliatesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AffiliatesForm, self).__init__(*args, **kwargs)
        model_fields = self.Meta.model._meta.get_fields()
        model_fields_names = []
        for model_field in model_fields:
            if not model_field.null:
                model_fields_names.append(model_field.name)

        x = model_fields_names.index('id')
        model_fields_names.pop(x)

        for field in model_fields_names:
            self.fields[field].widget.attrs = {
                'required': True
            }

    class Meta:
        model = Affiliates
        fields = '__all__'
```
And this is the forms serve function:
```python
def serve(self, request):
        from .forms import AffiliatesForm, AffiliationInlineForm

        AffiliationFormSet = inlineformset_factory(
            Affiliates,
            Affiliation,
            form=AffiliationInlineForm,
            fields=['person', 'affiliation', ],
            extra=1
        )
        form = AffiliatesForm()
        formset = AffiliationFormSet()

        if request.method == 'POST':
            form = AffiliatesForm(request.POST)
            formset = AffiliationFormSet(request.POST)
            print(form)
            print(formset)

            if form.is_valid() and formset.is_valid():
                form = form.save()
                formset = formset.save()

                return render(request, 'form_page_landing.html', {
                    'page': self,
                    'form': form,
                    'formset': formset,
                })
        else:
            form = AffiliatesForm()
            formset = AffiliationFormSet()

        return render(request, 'form_page.html', {
            'page': self,
            'form': form,
            'formset': formset,
        })
```

I have to say again, smart_selects doesn't works too in django admin.

**Comment by blag** [comment] 2016-10-13 14:39
Inlines were fixed in #148.

**Closed by blag** 2016-10-13 14:39 UTC
Labels: Possibly fixed

**Comment by SalahAdDin** [comment] 2016-10-14 03:12
Will be released soon?

**Comment by blag** [comment] 2016-10-14 04:06
Yep, I'm going to try to cut a release to PyPI tomorrow.
