### ISSUE TITLE
Select Field Filtered By More than one Field

### ISSUE THREAD

**Issue by bernatbonet** [digi604/django-smart-selects#17] opened 2011-04-12 10:36 UTC
I think it could be interesting fielter a select field by more than one model, i.e., I have a model that can be filtered by n models, because it have n foreign keys and it could be usefull filter it by more than one model.

**Comment by blag** [comment] 2016-10-22 09:56
I think this is outside the scope of this project. That would be incredibly difficult to actually implement with this project.

This is exactly the type of thing that django-autocomplete-light was designed for and could absolutely handle.

Due to that, I'm going to close this. But feel free to contribute more ideas!

**Closed by blag** 2016-10-22 09:56 UTC
