### ISSUE TITLE
django-smart-selects is not working with Jquery 3

### ISSUE THREAD

**Issue by werberth** [digi604/django-smart-selects#238] opened 2017-11-06 04:11 UTC
django-smart-selects is not working with Jquery 3, I add the CND of Jquery 3 in html and nothing happens with the forms. If I add the CDN of Jquery 2, django-smart-selects works normally.

**Comment by blag** [comment] 2017-11-07 05:56
First, I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. You even had to delete that entire template to continue!
To properly file an issue, you must fill out the issue template at:

https://github.com/digi604/django-smart-selects/blob/master/.github/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

(These pictures are just examples from a different repository but the process is the same.)

Additionally, this is a duplicate of #197. Please search through existing issues before opening new issues. Thanks!

**Closed by blag** 2017-11-07 05:56 UTC
