### ISSUE TITLE
Don't sort filtered choices

### ISSUE THREAD

**Issue by PetrDlouhy** [digi604/django-smart-selects#110] opened 2016-01-18 19:18 UTC
In `widgets.py` the filtered results are sorted by `sort_results` function. This seems to me to be unnecessary, at least in some cases, and could be quite slow. I think, it should be left on the query to sort on database side. Or at least this behaviour should be optional.

**Comment by blag** [comment] 2016-10-13 13:38
Duplicate of #46.

**Closed** 2016-10-13 13:39 UTC
Labels: Feature request
