### ISSUE TITLE
Django Smart Select works in admin page but doesn't work in template. Shows [HTTP/1.0 404 Not Found] in browser console

### ISSUE THREAD

**Issue by chukwumad** [digi604/django-smart-selects#226] opened 2017-07-13 09:43 UTC

**Comment by AmiNadim** [comment] 2017-10-12 06:40
**Issue Resolved Manually**


just add these three lines to the <head> section of your html template
```
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static '/smart-selects/admin/js/chainedfk.js' %}"></script>
    <script type="text/javascript" src="{% static '/smart-selects/admin/js/bindfields.js' %}"></script>
```

these are the links used in django admin.

**Comment by chukwumad** [comment] 2017-10-12 07:44
Thank you. I already solved the problem using the same solution you suggested. I appreciate.

**Comment by surfer190** [comment] 2017-11-06 13:12
Yes, I can confirm that this works but is it correct? The documentation does not mention it.

**Comment by blag** [comment] 2017-11-07 06:00
I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. You even had to delete all of that template before writing your own text! I put a lot of work into that issue template and you just ignored it! 😭 

Feel free to reopen this issue once you have filled out the issue template at:

https://github.com/digi604/django-smart-selects/blob/master/.github/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

Once you have done that I will take a look at this issue. Thanks!

(These pictures are just examples from a different repository but the process is the same.)

**Closed by blag** 2017-11-07 06:00 UTC
