### ISSUE TITLE
Can you cross more than one model boundary?

### ISSUE THREAD

**Issue by mark0978** [digi604/django-smart-selects#62] opened 2014-06-29 20:43 UTC
```
class CustomerDroplist(models.model):
    customer = models.ForeignKey(Customer)
    display = models.CharField(max_length=32)

class EmailAddressType(CustomerDroplist):  # reversion
    ....

class EmailAddress(models.Model):
    address_type = ChainedForeignKey(EmailAddressType,
                                     chained_field='address_type__customer',
                                     chained_model_field='customer',
                                     show_all=False,
                                     auto_choose=True)
    ....
```

Trying to use this in Admin with TabularInlines, but it appears there is no way to trigger the list of EmailAddressTypes based on the customer field of the main model that EmailAddress is linked to.

Am I just missing something?

**Comment by evandavey** [comment] 2015-05-27 01:20
+1

**Comment by DurandA** [comment] 2015-12-15 18:19
+1

**Comment by blag** [comment] 2016-10-22 09:32
No, this is partially implemented in #94. If somebody could take that and rebase it against the current master I would be really grateful.

**Comment by blag** [comment] 2016-10-22 10:39
Since this is a duplicate of #93, I'm going to close this.

**Closed by blag** 2016-10-22 10:39 UTC
Labels: Feature request, Question

**Comment by blag** [comment] 2017-05-10 23:52
As I explained in #94, this is a security incident waiting to happen, so I won't be accepting any PRs implementing this unless somebody can come up with a secure by default access control. Sorry!
